### ISSUE TITLE
interfaces2netplan: unexpected line ' up route add ... '

### ISSUE THREAD

**Issue by vilitux** [ossobv/vcutil#18]
We have the following configuration active in /etc/network/interfaces:
```
auto eth1
iface eth1 inet static
	address 192.168.1.3
	netmask 255.255.255.0
	up route add -net 10.0.0.0 netmask 255.255.255.0 gw 192.168.1.1
        down route del -net 10.0.0.0 netmask 255.255.255.0 gw 192.168.1.1
```

When using interfaces2netplan, it gives us the following stacktrace:
```
Traceback (most recent call last):
  File "/usr/bin/interfaces2netplan", line 358, in <module>
    main()
  File "/usr/bin/interfaces2netplan", line 353, in main
    files.show()
  File "/usr/bin/interfaces2netplan", line 166, in show
    yaml = self.get_yaml()
  File "/usr/bin/interfaces2netplan", line 145, in get_yaml
    ifile = InterfacesFile(long_file)
  File "/usr/bin/interfaces2netplan", line 186, in __init__
    self._parse()
  File "/usr/bin/interfaces2netplan", line 249, in _parse
    self._parse_context(context[1], config[context], line)
  File "/usr/bin/interfaces2netplan", line 292, in _parse_context
    raise ValueError('unexpected line {!r}'.format(line))
ValueError: unexpected line ' up route add -net 10.0.0.0 netmask 255.255.255.0 gw 192.168.1.1'
```

The expected output would've been something like this:
```
network:
  version: 2
  renderer: networkd
  ethernets:
    ens5:
      addresses:
       - 192.168.1.3/24
      gateway4: 192.168.1.1
      routes:
       - to: 10.0.0.0/24
         via: 192.168.1.1
```

**Comment by wdoekes** [comment]
Already fixed long long long ago in af91d3cfaa1da2631b1bc0f8ecba72aca6dd7079, yo!
